### ISSUE TITLE
hint characters seem to be ignored

### ISSUE THREAD

**Issue by Alok** [hbt/mouseless#100]
i just switched to `mouseless` from cvim since i was frustrated by the slow pace of development, but i've so far not been able to get it to work too well.

I have the setting `let hintcharacters = "qwfupzxycvmlp,asdhione"` but it seems to be ignored as chars like `r` and `t` show up in the link hints.

**Comment by hbt** [comment]
```
let mouselesshintcharacters = "dsafrewq,tgcx"
```

https://hbt.github.io/mouseless/tips.html#_hbt_cvimrc_configuration_example
https://gist.github.com/hbt/b3d6b753c5a060667582327b85300ba1

will look into adding a warning or something.

**Comment by hbt** [comment]
https://github.com/hbt/mouseless/issues/101

**Comment by Alok** [comment]
Thanks.
