### ISSUE TITLE
Tab switching doesn't seem to work anymore

### ISSUE THREAD

**Issue by x-ji** [hbt/mouseless#107]
Now tab switching doesn't work in either the original `chromium-vim` or in `mouseless`. Hitting `B` and then trying to go to a selected tab will have no effect.

A similar issue is reported at https://github.com/1995eaton/chromium-vim/issues/529. It can be fixed by using version 1.286 of cVim instead of 1.287. There must be something that caused the change between these two releases.

System: Ubuntu 16.04 LTS
Chrome: 57.0.2987.110 (64-bit)

**Comment by hbt** [comment]
bug confirmed
