### ISSUE TITLE
Doesn't load in Chrome 59

### ISSUE THREAD

**Issue by rosshadden** [hbt/mouseless#111]
I get the following error when trying to add the extension to the current google-chrome-beta channel:

```
Failed to load extension from: ~/dotfiles/lib/vendor/mouseless
Invalid value for 'content_scripts[0].matches[1]': Invalid scheme.
```

**Comment by hbt** [comment]
https://hbt.github.io/mouseless/installation.html

turn on flag chrome://flags/#extensions-on-chrome-urls

restart browser

load unpacked extension

**Comment by rosshadden** [comment]
Ohhh my bad.  I was switching to the beta channel to fix some GTK issues with Chrome and totally forgot I had to do that.
