### ISSUE TITLE
feature request: click element

### ISSUE THREAD

**Issue by wesamco** [hbt/mouseless#113]
Hi, it really looks like the cvim project is abandoned. 
------
at the end of the day, it's a graphical web browser, not a text editor.
we need a way to click an element. so we never have to touch the mouse while browsing.
like the `f` key press functionality, (labels all anchors & buttons) 
the `c` key press should label all elements excluding `div` & `span` elements.

here's how to simulate a click, i tested it, it worked.

```
function eventFire(el, etype){
  if (el.fireEvent) {
    el.fireEvent('on' + etype);
  } else {
    var evObj = document.createEvent('Events');
    evObj.initEvent(etype, true, false);
    el.dispatchEvent(evObj);
  }
}
```
usage: `eventFire(document.getElementById('mytest1'), 'click');`

I will try to add this feature and submit a PR, but first I'll have to read and understand the project to write a LOC & contribute.

**Comment by hbt** [comment]
too many elements arent worth clicking on.
you are better off using "siteFilters" (view doc)
https://hbt.github.io/mouseless/tips.html#_cool_custom_scripts
