### ISSUE TITLE
Muting tabs

### ISSUE THREAD

**Issue by rosshadden** [hbt/mouseless#120]
Is it feasible to add support for muting tabs?

I found [this extension](https://github.com/danhp/mute-tab-chrome/blob/master/src/background.js#L7-L9) which has code for doing it, but not sure how relevant or useful it is as the chrome API usage seems different than what is used here.

**Comment by hbt** [comment]
https://hbt.github.io/mouseless/commands.html#_tabs

```
muteTab
```

**Comment by rosshadden** [comment]
Oh I'm sorry... I had searched through github's UI for `mute` and didn't see any reference to it. Thanks.

**Comment by rosshadden** [comment]
More embarrassing is that it's already in my config.  I had already searched through the code (four months ago according to git history), found it, added it, and completely forgot about it.
