### ISSUE TITLE
latest google chrome crashes but not chromium

### ISSUE THREAD

**Issue by hbt** [hbt/mouseless#134]
Quick Fixes:

- disable chrome:// support in manifest
- disable/review the newtab.html and its creation 

Long term:

- figure out what changed between latest version and fix as chrome:// support is useful

**Comment by Alok** [comment]
this one has been killing me too. i've switched back to cvim for the time being.

**Comment by hbt** [comment]
in manifest.json

change 

`"matches": ["<all_urls>", "chrome://*/*"],`

to 

`"matches": ["<all_urls>"],`


It will fix the issue on google chrome.
I dont know why yet, I didnt bother investigating.
