### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by alok** [hbt/mouseless#152]
Pretty much the title.

**Comment by hbt** [comment]
Yes

- I still use it daily. 
- source https://github.com/1995eaton/chromium-vim gets merged whenever there is update
- issues / enhancements are logged https://github.com/hbt/mouseless/issues (most recent 2 weeks ago)

However, it is mature software and except for a few hard to fix bugs; it is stable and less in need of active development.
The enhancements are often great ideas but ROI is not there yet.


Feel free to let me know if a particular useful command could be a difference maker.
