### ISSUE TITLE
Prefix keys

### ISSUE THREAD

**Issue by averrin** [hbt/mouseless#29]
Hi. cVim looks like abandoned , but may be you can help me.
I want to use tmux-like shortcuts in cVim. 
```
<C-a>N - go to N tab
<C-a>h - prev tab
```

and others. Is it possible in cVim, or maybe in your fork?

**Comment by hbt** [comment]
map N goToTab
map h previousTab

view README -  the mapping name column 


Also, cVim is not officially abandoned. The author might be busy and providing support (like Q&A) takes time.

**Comment by averrin** [comment]
Oh, github ate prefix. Post updated.

**Comment by hbt** [comment]
Look into mapping the leader key but not sure it will work.


Does it work if you map each command manually? i.e 
```
<C-a>N - go to N tab
<C-a>h - prev tab
```

Maybe consider something other than ```C-a>```

**Comment by averrin** [comment]
Unfortunately, mappings with leader (not only <C-a>, but C-b, C-d and others) are not work=(

**Comment by hbt** [comment]
Sorry, not supported in this fork either. 

One thing you could do is use a key remapper - e.g xmodmap to remap C-a to a key like \ then use that key as the leader key in your cvimrc 

When typing C-a, xmodmap  would send \ instead. 

It's an easy workaround if you insist on having Control key as your leader key
