### ISSUE TITLE
map one key to 2 or more commands?

### ISSUE THREAD

**Issue by deluxghost** [hbt/mouseless#68]
like:
`map <key> :call somescript<CR>:open google<Space>`

**Comment by hbt** [comment]
current not supported but there is a workaround

```
parsing2lines() -> {{
var value = "call :source /home/hassen/.cvimrc<CR>";
Mappings.parseLine(value);
var value2 = "some other command";
Mappings.parseLine(value2);
}}
```

map tr :call parsing2lines<CR>


You could parse more than one line then map that script
