### ISSUE TITLE
Cannot map some keys.

### ISSUE THREAD

**Issue by amosbird** [hbt/mouseless#69]
These are some problematic key mappings,
```
imap <C-m> <Enter>
imap <C-j>	<Down>
imap <C-k>	<Up>
imap <M-b>	backwordWord
```

and `<C-w>` still binds to close current tab no matter whatever mapping is set for it.

**Comment by amosbird** [comment]
Ah, I find the place to map `<C-w>`, however, those key maps still don't work.

**Comment by hbt** [comment]
mind sharing how you fixed `<c-w>` ?

**Comment by amosbird** [comment]
In the `keyboard shortcuts` menu ![](https://ptpb.pw/dZBN.jpg)

make configuration like this,
![](https://ptpb.pw/gZ-H.jpg)

**Comment by hbt** [comment]
Thanks.

Most definitely a bug and a review of those keyboard shortcuts needs to be made to make sure it's compatible with the mappings. I don't use them, I only use the mappings.
