### ISSUE TITLE
Editing contenteditable nodes in external editor

### ISSUE THREAD

**Issue by rosshadden** [hbt/mouseless#74]
Might it be feasible to allow editing `div`s with `contenteditable` set, as if they were text fields?

**Comment by hbt** [comment]
yes, doable. 

- add a class to that div
- add class to siteFilters
- hints now detect the div
- open it via external editor and its html is loaded

All commands already exist but lack of good documentation.

I'm working on a "tips/example" page for stuff like that and if you do the above, it'd be great to share the code here.

**Comment by rosshadden** [comment]
What you suggested works, other than the error fixed in #75.

**Comment by rosshadden** [comment]
Actually what you suggested is unnecessary.  It works without adding anything to `siteFilters` (with the aforementioned fix that is).

**Comment by hbt** [comment]
Agreed. Thanks for the fix.
