### ISSUE TITLE
Follow link not working

### ISSUE THREAD

**Issue by Kerruba** [hbt/mouseless#82]
Hello,
first of all thanks for take the project ahead.
I'm finding the follow link mode not working. When I type "f", a <Follow link> label appear on the top right of the page, but no link is highlighted or shown.

The problem is in hints.js, row 641:
```
  var hintKeys = settings.mouselesshintcharacters
  var linkHintCharacters = hintKeys
```
settings.mouselesshintcharacters is undefined. 
The problem is solved defining the hintcharacters in the settings.

Possible solution is to define some default value. Not sure is already the case.

**Comment by hbt** [comment]
valid bug + good fix. will do shortly.

meanwhile, add this to local config

```
let hintcharacters = "dsafrewqtgcx"
let mouselesshintcharacters = "dsafrewq,tgcx"
```

**Comment by Kerruba** [comment]
Possibly you just need
```
let mouselesshintcharacters = "dsafrewq,tgcx"
```

In my case I've used
```
let mouselesshintcharacters = "1234"
```

**Comment by hbt** [comment]
ref https://github.com/hbt/mouseless/commit/d51029bb0d40f0ee827e4b2b1be917f9637719de
