### ISSUE TITLE
Operation on the pages that failed to load/in the process of loading

### ISSUE THREAD

**Issue by Stvad** [hbt/mouseless#96]
I'm not sure how feasible it is, but it'd be nice to be able to work with extension even if the content of the page failed to load properly (you might want to switch, to another tab, close this one, or open another url). Right now if the page have failed to load or in the process of loading - plugin functionality is unavailable.

**Comment by hbt** [comment]
I've seen multiple solutions to this problem but often poor implementations. 

Solutions: 

1. load a blank.html, load the extension then redirect/load  URL.
2. use the script injection to load something slightly before the page renders -- the way many stylesheet toggler extensions work


Generally, this issue doesn't happen frequently enough to warrant a complex solution. The main issue is often the site itself or the computer speed.

**Comment by hbt** [comment]
Note: If you have a better solution, please suggest/implement it and I will pull it
