### ISSUE TITLE
Don't execute command if non-mapped modifier key is toggled

### ISSUE THREAD

**Issue by Stvad** [hbt/mouseless#97]
Say I have a web application that provides some shortcuts. 
For example, Asana has a bunch of shortcuts in the Tab+symbol format.

It's not overlapping with anything that this plugin provides, yet when I press Tab+/ - plugin search is activated instead of Asana search. I think that commands should be ignored if some modifier key is pressed, so it won't intercept commands not meant for it.

Another thing - it would be great if what gets priority in handling keystrokes (web application or extension) would've been configurable on per app basis.

**Comment by hbt** [comment]
check custom site mapping 
e.g

```
site '*://mail.google.com/*' {
  set ignorenumerickeys 
  unmap `
}
site '*://*.reddit.com/*' {
      " use reddit RES extension instead
      unmap j
      unmap k
      unmap J
      unmap K


      unmap a
      unmap s

      
}
```

also, check passKeys / passMode commands

**Comment by Stvad** [comment]
I don't want to disable cVim mappings. The will still perfectly well in the described scenario. 
The point here is that it doesn't make sense to treat Tab+q (true for any other keys pressed in combination) exactly the same as just 'q'. 
It's already true for some combinations/modifiers, e.g. Alt+f is treated differently than just 'f', I think it makes sense to extend behavior to other combinations.

**Comment by hbt** [comment]
you can map asana combinations to passkey

**Comment by Stvad** [comment]
It's not the point, as I said I see it as a general issue. I don't think that bindings should be invoked when the corresponding button is pressed while the user holds any other button down (if it's not a part of mapped combination).
